import bcrypt from 'bcryptjs'

 const data = {
   colors: [{
     color: 'red',
     sizes:[],
     productRef: null
   },
   {
    color: 'blue',
    sizes:[],
    productRef: null

  },
  {
    color: 'yellow',
    sizes:[],
    productRef: null

  },
   ],
   sizes:[{
     size:"s",
     countInStock: null,
     colorRef: null
     
   },
   {
    size:"m",
    countInStock: null,
    colorRef: null
  },
  {
    size:"l",
    countInStock: null,
    colorRef: null
  },
  {
    size:"xl",
    countInStock: null,
    colorRef: null
  }
  ],
  users:[
  {
    name:'Valentin',
    email:'admin@example.com',
    password: bcrypt.hashSync('1234', 8),
    isAdmin: true,
  },
  {
    name:'Maelle',
    email:'user@example.com',
    password: bcrypt.hashSync('12345', 8),
    isAdmin: false,
  },
],
  products: [
    {
      image: "../image/pants/pant1.jpg",
      image2: "../image/pants/pant1-2.jpg",
      image3: "../image/pants/pant1-3.jpg",
      image4: "../image/pants/pant1-4.jpg",
      image5: "../image/pants/pant1-5.jpg",
      name: "Jean slim #Tom 4L",
      category: "Pant",
      brand: "Jules",
      color:'blue',
      price: 49.99,
      rating: 4.5,
      numberOfReview: 10,
      description:"Inimitable, irremplaçable, ce jean homme slim bleu stone en toile lavée se patine au fil des jours et se plie à votre mode de vie ! Très confortable, sa toile vieillit joliment dans le temps, et sa coupe ajustée confectionnée en denim structure la silhouette 5 poches. Fermeture bouton et glissière. Existe en 4 longueurs."
      },
      {
        image: "../image/pants/pant2.jpg",
        image2: "../image/pants/pant2-2.jpg",
        image3: "../image/pants/pant2-3.jpg",
        image4: "../image/pants/pant2-4.jpg",
        image5: "../image/pants/pant2-5.jpg",
        name: "Jean Urbanflex 4 longueurs noir lavé - Noir",
        category: "Pant",
        brand: "Jules",
        color:'blue',
        price: 49.99,
        rating: 4.5,
        numberOfReview: 10,
        description:"Grand classique du dressing masculin, ce jean homme slim affiche une allure actuelle avec un coloris noir lavé facile à porter, et se décline en 4 longueurs pour un ajustement optimal à chaque morphologie.5 poches. Fermeture bouton et glissière."
      },
      {
        image: "../image/pants/pant3.jpg",
        image2: "../image/pants/pant3-2.jpg",
        image3: "../image/pants/pant3-3.jpg",
        image4: "../image/pants/pant3-4.jpg",
        image5: "../image/pants/pant3-5.jpg",
        name: "Jean straight Ben 4L",
        category: "Pant",
        brand: "Jules",
        color:'blue',
        price: 49.99,
        rating: 4.5,
        numberOfReview: 10,
        description:"Ce jean homme straight bleu s'adapte à toutes les morphologies avec sa coupe droite très confortable. Indispensable, indémodable, ce jean affiche un style relax en toutes occasions.5 poches. Fermeture bouton et glissière."
      },
      {
        image: "../image/pants/pant4.jpg",
        image2: "../image/pants/pant4-2.jpg",
        image3: "../image/pants/pant4-3.jpg",
        image4: "../image/pants/pant4-4.jpg",
        image5: "../image/pants/pant4-5.jpg",
        name: "Jean Skinny noir lave",
        category: "Pant",
        brand: "Jules",
        color:'blue',
        price: 29.99,
        rating: 4.5,
        numberOfReview: 10,
        description:"Ce jean homme skinny noir lavé possède une allure résolument tendance avec sa coupe très ajustée et son coloris noir lavé. Indispensable, indémodable, ce jean affiche un style relax en toutes occasions."
      },{
      image: "../image/pants/pant5.jpg",
      image2: "../image/pants/pant5-2.jpg",
      image3: "../image/pants/pant5-3.jpg",
      image4: "../image/pants/pant5-4.jpg",
      image5: "../image/pants/pant5-5.jpg",
      name: "Jean Straight #Ben ",
      category: "Pant",
      brand: "Jules",
      color:'beige',
      price: 59.99,
      rating: 4.5,
      numberOfReview: 10,
      description:"Ce jean homme straight s'adapte à toutes les morphologies avec sa coupe droite très confortable. Il affiche une allure résolument actuelle avec une matière résinée et un coloris bleu grisé lavé."
    },
    {
    image: "../image/pants/pant6.jpg",
    image2: "../image/pants/pant6-2.jpg",
    image3: "../image/pants/pant6-3.jpg",
    image4: "../image/pants/pant6-4.jpg",
    image5: "../image/pants/pant6-5.jpg",
    name: "Chino coupe slim Simon ",
    category: "Pant",
    brand: "Jules",
    color:'black',
    price: 39.99,
    rating: 4.5,
    numberOfReview: 10,
    description:"Ce chino homme associe l'élégance d'une coupe slim et le confort du twill. Ensuite, tout est question d'association ! Le chino se fait chic avec une chemise unie et une paire de derbies, casual avec une touche colorée ou un bel imprimé, ou carrément chic avec une chemise impeccable et des chaussures de ville. Fermeture boutons et glissière. 2 poches italiennes devant, 2 poches passepoilées au dos."
  },{
    image: "../image/pants/pant7.jpg",
    image2: "../image/pants/pant7-2.jpg",
    image3: "../image/pants/pant7-3.jpg",
    image4: "../image/pants/pant7-4.jpg",
    image5: "../image/pants/pant7-5.jpg",
    name: "Chino slim en velours",
    category: "Pant",
    brand: "Jules",
    color:'red',
    price: 59.99,
    rating: 4.5,
    numberOfReview: 10,
    description:"Ce chino homme slim se renouvelle en douceur avec un tissage en velours côtelé, confortable et élégant."
  },
  {
    image: "../image/pants/pant8.jpg",
    image2: "../image/pants/pant8-2.jpg",
    image3: "../image/pants/pant8-3.jpg",
    image4: "../image/pants/pant8-4.jpg",
    image5: "../image/pants/pant8-5.jpg",
    name: "Pantalon 5 poches slim",
    category: "Pant",
    brand: "Jules",
    color:'black',
    price: 25.99,
    color:'red',
    rating: 4.5,
    numberOfReview: 10,
    description:"Valeur sûre du dressing masculin, ce pantalon 5 poches affiche un style authentique"
  },
  {
    image: "../image/pants/pant9.jpg",
    image2: "../image/pants/pant9-2.jpg",
    image3: "../image/pants/pant9-3.jpg",
    image4: "../image/pants/pant9-4.jpg",
    image5: "../image/pants/pant9-5.jpg",
    name: "Chino slim à carreaux",
    category: "Pant",
    brand: "Jules",
    color:'red',
    price: 29.99,
    rating: 4.5,
    numberOfReview: 10,
    description:"Cette saison, le chino homme se tient à carreaux avec un motif graphique toujours chic pour une tenue zéro défaut sur une coupe slim actuelle et élégante."
  },
  {
    image: "../image/pants/pant10.jpg",
    image2: "../image/pants/pant10-2.jpg",
    image3: "../image/pants/pant10-3.jpg",
    image4: "../image/pants/pant10-4.jpg",
    image5: "../image/pants/pant10-5.jpg",
    name: "Pantalon 5 poches slim",
    color: 'Blue',
    category: "Pant",
    brand: "Jules",
    color:'brown',
    price: 25.99,
    rating: 4.5,
    numberOfReview: 10,
    description:"Valeur sûre du dressing masculin, ce pantalon 5 poches affiche un style authentique"
  },
  {
    image: "../image/tshirt/tshirt1.jpg",
    image2: "../image/tshirt/tshirt1-2.jpg",
    image3: "../image/tshirt/tshirt1-3.jpg",
    image4: "../image/tshirt/tshirt1-4.jpg",
    image5: "../image/tshirt/tshirt1-5.jpg",
    name: "tee-shirt col roulé",
    category: "T-shirt",
    brand: "Jules",
    color:'grey',
    price:15.95,
    rating: 4.5,
    numberOfReview: 10,
    description:"Manches longues. Col en bords côtes pour une tenue et un tomber parfait.Le mannequin mesure 1m92 et porte une taille M."
  },{
    image: "../image/tshirt/tshirt2.jpg",
    image2: "../image/tshirt/tshirt2-2.jpg",
    image3: "../image/tshirt/tshirt2-3.jpg",
    image4: "../image/tshirt/tshirt2-4.jpg",
    image5: "../image/tshirt/tshirt2-5.jpg",
    name: "tee-shirt col roulé",
    category: "T-shirt",
    brand: "Jules",
    color:'white',
    price:15.95,
    rating: 4.5,
    numberOfReview: 10,
    description:"Manches longues. Col en bords côtes pour une tenue et un tomber parfait.Le mannequin mesure 1m92 et porte une taille M."
  },{
    image: "../image/tshirt/tshirt3.jpg",
    image2: "../image/tshirt/tshirt3-2.jpg",
    image3: "../image/tshirt/tshirt3-3.jpg",
    image4: "../image/tshirt/tshirt3-4.jpg",
    image5: "../image/tshirt/tshirt3-5.jpg",
    name: "tee-shirt col roulé",
    category: "T-shirt",
    brand: "Jules",
    color:'lightgrey',
    price:15.95,
    rating: 4.5,
    numberOfReview: 10,
    description:"Manches longues. Col en bords côtes pour une tenue et un tomber parfait.Le mannequin mesure 1m92 et porte une taille M."
  },
  {
    image: "../image/tshirt/tshirt4.jpg",
    image2: "../image/tshirt/tshirt4-2.jpg",
    image3: "../image/tshirt/tshirt4-3.jpg",
    image4: "../image/tshirt/tshirt4-4.jpg",
    image5: "../image/tshirt/tshirt4-5.jpg",
    name: "-shirt Région BRETAGNE",
    category: "T-shirt",
    brand: "Jules",
    color:'blue',
    price:15.95,
    rating: 4.5,
    numberOfReview: 10,
    description:"Clin d'œil à la région Bretagne, ce tee-shirt homme à manches courtes clame haut et fort sa particularité et affiche un beau motif graphique sur une coupe droite, confortable et agréable à porter. Il se porte avec un jean, un bermuda ou un pantalon chino pour un style décontracté toute l'année."
  },
  {
    image: "../image/tshirt/tshirt5.jpg",
    image2: "../image/tshirt/tshirt5-2.jpg",
    image3: "../image/tshirt/tshirt5-3.jpg",
    image4: "../image/tshirt/tshirt5-4.jpg",
    image5: "../image/tshirt/tshirt5-5.jpg",
    name: "t-shirt col tunisien",
    category: "T-shirt",
    brand: "Jules",
    color:'white',
    price:19.99,
    rating: 4.5,
    numberOfReview: 10,
    description:"Essentiel et intemporel, ce tee-shirt homme à col tunisien est confectionné dans une belle matière fantaisie légèrement chinée."
  },{
    image: "../image/tshirt/tshirt6.jpg",
    image2: "../image/tshirt/tshirt6-2.jpg",
    image3: "../image/tshirt/tshirt6-3.jpg",
    image4: "../image/tshirt/tshirt6-4.jpg",
    image5: "../image/tshirt/tshirt6-5.jpg",
    name: "t-shirt col tunisien",
    category: "T-shirt",
    brand: "Jules",
    color:'brown',
    price:19.99,
    rating: 4.5,
    numberOfReview: 10,
    description:"Essentiel et intemporel, ce tee-shirt homme à col tunisien est confectionné dans une belle matière fantaisie légèrement chinée."
  },{
    image: "../image/tshirt/tshirt7.jpg",
    image2: "../image/tshirt/tshirt7-2.jpg",
    image3: "../image/tshirt/tshirt7-3.jpg",
    image4: "../image/tshirt/tshirt7-4.jpg",
    image5: "../image/tshirt/tshirt7-5.jpg",
    name: "t-shirt col tunisien",
    category: "T-shirt",
    brand: "Jules",
    color:'yellow',
    price:19.99,
    rating: 4.5,
    numberOfReview: 10,
    description:"Essentiel et intemporel, ce tee-shirt homme à col tunisien est confectionné dans une belle matière fantaisie légèrement chinée."
  },
  {
    image: "../image/pull/pull1.jpg",
    image2: "../image/pull/pull1-2.jpg",
    image3: "../image/pull/pull1-3.jpg",
    image4: "../image/pull/pull1-4.jpg",
    image5: "../image/pull/pull1-5.jpg",
    name: "tpull col roulé torsadé",
    category: "Pull",
    brand: "Jules",
    color:'white',
    price:49.99,
    rating: 4.5,
    numberOfReview: 10,
    description:"Ce pull homme col roulé est confectionné dans une grosse maille torsadée chaude et moelleuse contenant de la laine. Le jeu de points sur l'ensemble du pull lui donne un style très élégant."
  },
  {
    image: "../image/pull/pull2.jpg",
    image2: "../image/pull/pull2-2.jpg",
    image3: "../image/pull/pull2-3.jpg",
    image4: "../image/pull/pull2-4.jpg",
    image5: "../image/pull/pull2-5.jpg",
    name: "tpull col roulé torsadé",
    category: "Pull",
    brand: "Jules",
    color:'brown',
    price:49.99,
    rating: 4.5,
    numberOfReview: 10,
    description:"Ce pull homme col roulé est confectionné dans une grosse maille torsadée chaude et moelleuse contenant de la laine. Le jeu de points sur l'ensemble du pull lui donne un style très élégant."
  },{
    image: "../image/pull/pull3.jpg",
    image2: "../image/pull/pull3-2.jpg",
    image3: "../image/pull/pull3-3.jpg",
    image4: "../image/pull/pull3-4.jpg",
    image5: "../image/pull/pull3-5.jpg",
    name: "tpull col roulé torsadé",
    category: "Pull",
    brand: "Jules",
    color:'grey',
    price:49.99,
    rating: 4.5,
    numberOfReview: 10,
    description:"Ce pull homme col roulé est confectionné dans une grosse maille torsadée chaude et moelleuse contenant de la laine. Le jeu de points sur l'ensemble du pull lui donne un style très élégant."
  },
  {
    image: "../image/pull/pull4.jpg",
    image2: "../image/pull/pull4-2.jpg",
    image3: "../image/pull/pull4-3.jpg",
    image4: "../image/pull/pull4-4.jpg",
    image5: "../image/pull/pull4-5.jpg",
    name: "Pull col châle colorblock mouliné",
    category: "Pull",
    brand: "Jules",
    color:'green',
    price:49.99,
    rating: 4.5,
    numberOfReview: 10,
    description:"Graphique et original, ce pull homme à col châle affiche une maille moulinée en coton, avec jeu points et de couleurs effet colorblock."
  },
  {
    image: "../image/pull/pull5.jpg",
    image2: "../image/pull/pull5-2.jpg",
    image3: "../image/pull/pull5-3.jpg",
    image4: "../image/pull/pull5-4.jpg",
    image5: "../image/pull/pull5-5.jpg",
    name: "Graphique et original, ce pull homme à col châle affiche une maille moulinée en coton, avec jeu points et de couleurs effet colorblock.",
    category: "Pull",
    brand: "Jules",
    color:'blue',
    price:49.99,
    rating: 4.5,
    numberOfReview: 10,
    description:"Graphique et original, ce pull homme à col châle affiche une maille moulinée en coton, avec jeu points et de couleurs effet colorblock."
  },
  {
    image: "../image/pull/pull6.jpg",
    image2: "../image/pull/pull6-2.jpg",
    image3: "../image/pull/pull6-3.jpg",
    image4: "../image/pull/pull6-4.jpg",
    image5: "../image/pull/pull6-5.jpg",
    name: "Pull col châle colorblock mouliné",
    category: "Pull",
    brand: "Jules",
    color:'purple',
    price:49.99,
    rating: 4.5,
    numberOfReview: 10,
    description:"Pull col châle colorblock mouliné"
  },
  {
    image: "../image/sweat/sweat1.jpg",
    image2: "../image/sweat/sweat1-2.jpg",
    image3: "../image/sweat/sweat1-3.jpg",
    image4: "../image/sweat/sweat1-4.jpg",
    image5: "../image/sweat/sweat1-5.jpg",
    name: "Sweat zippée à capuche",
    category: "Sweat",
    brand: "Jules",
    color:'white',
    price:49.99,
    rating: 4.5,
    numberOfReview: 10,
    description:"L'essentiel du style casual est dans cesweat homme zippé à capuche : confectionné dans un molleton gratté bien épais, chaud et douillet, ce sweat zippé uni décline une belle game de coloris, souligné par le biais contrasté le long de la fermeture zippée."
  },{
    image: "../image/sweat/sweat2.jpg",
    image2: "../image/sweat/sweat2-2.jpg",
    image3: "../image/sweat/sweat2-3.jpg",
    image4: "../image/sweat/sweat2-4.jpg",
    image5: "../image/sweat/sweat2-5.jpg",
    name: "Sweat zippée à capuche",
    category: "Sweat",
    brand: "Jules",
    color:'brown',
    price:49.99,
    rating: 4.5,
    numberOfReview: 10,
    description:"L'essentiel du style casual est dans cesweat homme zippé à capuche : confectionné dans un molleton gratté bien épais, chaud et douillet, ce sweat zippé uni décline une belle game de coloris, souligné par le biais contrasté le long de la fermeture zippée."
  },{
    image: "../image/sweat/sweat3.jpg",
    image2: "../image/sweat/sweat3-2.jpg",
    image3: "../image/sweat/sweat3-3.jpg",
    image4: "../image/sweat/sweat3-4.jpg",
    image5: "../image/sweat/sweat3-5.jpg",
    name: "Sweat zippée à capuche",
    category: "Sweat",
    brand: "Jules",
    color:'black',
    price:49.99,
    rating: 4.5,
    numberOfReview: 10,
    description:"L'essentiel du style casual est dans cesweat homme zippé à capuche : confectionné dans un molleton gratté bien épais, chaud et douillet, ce sweat zippé uni décline une belle game de coloris, souligné par le biais contrasté le long de la fermeture zippée."
  },{
    image: "../image/sweat/sweat4.jpg",
    image2: "../image/sweat/sweat4-2.jpg",
    image3: "../image/sweat/sweat4-3.jpg",
    image4: "../image/sweat/sweat4-4.jpg",
    image5: "../image/sweat/sweat4-5.jpg",
    name: "Sweat à capuche en molleton uni",
    category: "Sweat",
    brand: "Jules",
    color:'red',
    price:39.99,
    rating: 4.5,
    numberOfReview: 10,
    description:"On enfile avec bonheur ce sweat homme à capuche en molleton gratté épais, chaud et incroyablement douillet. Ce sweat uni décline une belle gamme de coloris, qui s'harmonisent facilement avec toutes vos tenues"
  },{
    image: "../image/sweat/sweat5.jpg",
    image2: "../image/sweat/sweat5-2.jpg",
    image3: "../image/sweat/sweat5-3.jpg",
    image4: "../image/sweat/sweat5-4.jpg",
    image5: "../image/sweat/sweat5-5.jpg",
    name: "Sweat à capuche en molleton uni",
    category: "Sweat",
    brand: "Jules",
    color:'yelow',
    price:39.99,
    rating: 4.5,
    numberOfReview: 10,
    description:"On enfile avec bonheur ce sweat homme à capuche en molleton gratté épais, chaud et incroyablement douillet. Ce sweat uni décline une belle gamme de coloris, qui s'harmonisent facilement avec toutes vos tenues"
  },{
    image: "../image/sweat/sweat6.jpg",
    image2: "../image/sweat/sweat6-2.jpg",
    image3: "../image/sweat/sweat6-3.jpg",
    image4: "../image/sweat/sweat6-4.jpg",
    image5: "../image/sweat/sweat6-5.jpg",
    name: "Sweat à capuche en molleton uni",
    category: "Sweat",
    brand: "Jules",
    color:'orange',
    price:39.99,
    rating: 4.5,
    numberOfReview: 10,
    description:"On enfile avec bonheur ce sweat homme à capuche en molleton gratté épais, chaud et incroyablement douillet. Ce sweat uni décline une belle gamme de coloris, qui s'harmonisent facilement avec toutes vos tenues"
  },{
    image: "../image/shirt/shirt1.jpg",
    image2: "../image/shirt/shirt1-2.jpg",
    image3: "../image/shirt/shirt1-3.jpg",
    image4: "../image/shirt/shirt1-4.jpg",
    image5: "../image/shirt/shirt1-5.jpg",
    name: "Chemise flanelle à carreaux ",
    category: "Shirt",
    brand: "Jules",
    color:'pink',
    price:39.99,
    rating: 4.5,
    numberOfReview: 10,
    description:"On enfile avec bonheur cette chemise à gros carreaux vichy en flanelle douce et chaude. Elle porte se boutonnée ou ouverte sur un tee-shirt, façon surchemise pour une tenue casual confortable et stylée."
  },{
    image: "../image/shirt/shirt2.jpg",
    image2: "../image/shirt/shirt2-2.jpg",
    image3: "../image/shirt/shirt2-3.jpg",
    image4: "../image/shirt/shirt2-4.jpg",
    image5: "../image/shirt/shirt2-5.jpg",
    name: "Chemise flanelle à carreaux ",
    category: "Shirt",
    brand: "Jules",
    color:'blue',
    price:39.99,
    rating: 4.5,
    numberOfReview: 10,
    description:"On enfile avec bonheur cette chemise à gros carreaux vichy en flanelle douce et chaude. Elle porte se boutonnée ou ouverte sur un tee-shirt, façon surchemise pour une tenue casual confortable et stylée."
  },{
    image: "../image/shirt/shirt3.jpg",
    image2: "../image/shirt/shirt3-2.jpg",
    image3: "../image/shirt/shirt3-3.jpg",
    image4: "../image/shirt/shirt3-4.jpg",
    image5: "../image/shirt/shirt3-5.jpg",
    name: "Chemise flanelle à carreaux ",
    category: "Shirt",
    brand: "Jules",
    color:'white',
    price:39.99,
    rating: 4.5,
    numberOfReview: 10,
    description:"On enfile avec bonheur cette chemise à gros carreaux vichy en flanelle douce et chaude. Elle porte se boutonnée ou ouverte sur un tee-shirt, façon surchemise pour une tenue casual confortable et stylée."
  },
  {
    image: "../image/shirt/shirt4.jpg",
    image2: "../image/shirt/shirt4-2.jpg",
    image3: "../image/shirt/shirt4-3.jpg",
    image4: "../image/shirt/shirt4-4.jpg",
    image5: "../image/shirt/shirt4-5.jpg",
    name: "Chemise regular à carreaux ",
    category: "Shirt",
    brand: "Jules",
    color:'green',
    price:29.99,
    rating: 4.5,
    numberOfReview: 10,
    description:"Incontournable du dressing masculin, cette chemise homme à carreaux est confectionnée en twill souple et doux avec un aspect légèrement satiné pour une allure simple et fraîche."
  },
  {
    image: "../image/shirt/shirt5.jpg",
    image2: "../image/shirt/shirt5-2.jpg",
    image3: "../image/shirt/shirt5-3.jpg",
    image4: "../image/shirt/shirt5-4.jpg",
    image5: "../image/shirt/shirt5-5.jpg",
    name: "Chemise regular à carreaux ",
    category: "Shirt",
    brand: "Jules",
    color:'brown',
    price:29.99,
    rating: 4.5,
    numberOfReview: 10,
    description:"Incontournable du dressing masculin, cette chemise homme à carreaux est confectionnée en twill souple et doux avec un aspect légèrement satiné pour une allure simple et fraîche."
  },
  {
    image: "../image/shirt/shirt6.jpg",
    image2: "../image/shirt/shirt6-2.jpg",
    image3: "../image/shirt/shirt6-3.jpg",
    image4: "../image/shirt/shirt6-4.jpg",
    image5: "../image/shirt/shirt6-5.jpg",
    name: "Chemise slim unie ",
    category: "Shirt",
    brand: "Jules",
    color:'black',
    price:25.99,
    rating: 4.5,
    numberOfReview: 10,
    description:"Cette chemise slim à manches longues fait partie des must-have du dressing masculin. Unie, elle est confectionnée en popeline stretch pour plus de confort. Sa coupe cintrée et son col français conviennent parfaitement à un look urbain, associée à un chino slim par exemple."
    }  ,
  {
    image: "../image/shirt/shirt7.jpg",
    image2: "../image/shirt/shirt7-2.jpg",
    image3: "../image/shirt/shirt7-3.jpg",
    image4: "../image/shirt/shirt7-4.jpg",
    image5: "../image/shirt/shirt7-5.jpg",
    name: "Chemise slim unie ",
    category: "Shirt",
    brand: "Jules",
    color:'grey',
    price:25.99,
    rating: 4.5,
    numberOfReview: 10,
    description:"Cette chemise slim à manches longues fait partie des must-have du dressing masculin. Unie, elle est confectionnée en popeline stretch pour plus de confort. Sa coupe cintrée et son col français conviennent parfaitement à un look urbain, associée à un chino slim par exemple."
  },
  {
    image: "../image/shirt/shirt8.jpg",
    image2: "../image/shirt/shirt8-2.jpg",
    image3: "../image/shirt/shirt8-3.jpg",
    image4: "../image/shirt/shirt8-4.jpg",
    image5: "../image/shirt/shirt8-5.jpg",
    name: "Chemise slim unie ",
    category: "Shirt",
    brand: "Jules",
    color:'green',
    price:25.99,
    rating: 4.5,
    numberOfReview: 10,
    description:"Cette chemise slim à manches longues fait partie des must-have du dressing masculin. Unie, elle est confectionnée en popeline stretch pour plus de confort. Sa coupe cintrée et son col français conviennent parfaitement à un look urbain, associée à un chino slim par exemple."
  },
  {
    image: "../image/manteau/manteau1.jpg",
    image2: "../image/manteau/manteau1-2.jpg",
    image3: "../image/manteau/manteau1-3.jpg",
    image4: "../image/manteau/manteau1-4.jpg",
    image5: "../image/manteau/manteau1-5.jpg",
    name: "Manteau 3/4 col tailleur",
    category: "Manteau",
    brand: "Jules",
    color:'yellow',
    price:129.99,
    rating: 4.5,
    numberOfReview: 10,
    description:"et automne, le manteau homme 3/4 joue la carte de l'élégance et réchauffe vos looks de rentrée avec un tissage qui contient de la laine et un col tailleur élégant."
  },
  {
    image: "../image/manteau/manteau2.jpg",
    image2: "../image/manteau/manteau2-2.jpg",
    image3: "../image/manteau/manteau2-3.jpg",
    image4: "../image/manteau/manteau2-4.jpg",
    image5: "../image/manteau/manteau2-5.jpg",
    name: "Manteau 3/4 col tailleur",
    category: "Manteau",
    brand: "Jules",
    color:'red',
    price:129.99,
    rating: 4.5,
    numberOfReview: 10,
    description:"et automne, le manteau homme 3/4 joue la carte de l'élégance et réchauffe vos looks de rentrée avec un tissage qui contient de la laine et un col tailleur élégant."
  },
  {
    image: "../image/manteau/manteau3.jpg",
    image2: "../image/manteau/manteau3-2.jpg",
    image3: "../image/manteau/manteau3-3.jpg",
    image4: "../image/manteau/manteau3-4.jpg",
    image5: "../image/manteau/manteau3-5.jpg",
    name: "Manteau ski déperlant",
    category: "Manteau",
    brand: "Jules",
    color:'orange',
    price:89.99,
    rating: 4.5,
    numberOfReview: 10,
    description:"Conçu en matière déperlante et doté d'une capuche avec fausse fourrure amovible, ce blouson homme vous accompagne tout l'hiver. Il possède de nombreuses poches et s'associe à merveille avec un jean ou un pantalon chino."
  },
  {
    image: "../image/manteau/manteau4.jpg",
    image2: "../image/manteau/manteau4-2.jpg",
    image3: "../image/manteau/manteau4-3.jpg",
    image4: "../image/manteau/manteau4-4.jpg",
    image5: "../image/manteau/manteau4-5.jpg",
    name: "Manteau ski déperlant",
    category: "Manteau",
    brand: "Jules",
    color:'purple',
    price:89.99,
    rating: 4.5,
    numberOfReview: 10,
    description:"Conçu en matière déperlante et doté d'une capuche avec fausse fourrure amovible, ce blouson homme vous accompagne tout l'hiver. Il possède de nombreuses poches et s'associe à merveille avec un jean ou un pantalon chino."
  },
  {
    image: "../image/manteau/manteau5.jpg",
    image2: "../image/manteau/manteau5-2.jpg",
    image3: "../image/manteau/manteau5-3.jpg",
    image4: "../image/manteau/manteau5-4.jpg",
    image5: "../image/manteau/manteau5-5.jpg",
    name: "Blouson velours côtelé ",
    category: "Manteau",
    brand: "Jules",
    color:'green',
    price:69.99,
    rating: 4.5,
    numberOfReview: 10,
    description:"On enfile avec bonheur ce blouson homme en velours côtelé doublé de faux mouton chaud et doux"
  },
  {
    image: "../image/manteau/manteau6.jpg",
    image2: "../image/manteau/manteau6-2.jpg",
    image3: "../image/manteau/manteau6-3.jpg",
    image4: "../image/manteau/manteau6-4.jpg",
    image5: "../image/manteau/manteau6-5.jpg",
    name: "Blouson velours côtelé ",
    category: "Manteau",
    brand: "Jules",
    color:'black',
    price:69.99,
    rating: 4.5,
    numberOfReview: 10,
    description:"On enfile avec bonheur ce blouson homme en velours côtelé doublé de faux mouton chaud et doux"
  },
  ],
};

export default data
