export const ORDER_CREATE_REQUEST = 'ORDER_CREATE_REQUEST';
export const ORDER_SUCCESS_REQUEST = 'ORDER_SUCCESS_REQUEST';
export const ORDER_FAIL_REQUEST = 'ORDER_FAIL_REQUEST';
export const ORDER_RESET_REQUEST = 'ORDER_RESET_REQUEST'

export const ORDER_DETAILS_REQUEST = 'ORDER_DETAILS_REQUEST'
export const ORDER_DETAILS_SUCCESS = 'ORDER_DETAILS_SUCCESS'
export const ORDER_DETAILS_FAIL = 'ORDER_DETAILS_REQUEST'
// export const ORDER_DETAILS_REQUEST = 'ORDER_DETAILS_REQUEST'