export const USER_SIGNIN_REQUEST = 'USER_SIGNIN_REQUEST'
export const USER_SIGNIN_SUCCESS = 'USER_SIGNIN_SUCCES'
export const USER_SIGNIN_FAIL = 'USER_SIGNIN_FAIL'
export const USER_SIGNIN_SIGNOUT = 'USER_SIGNIN_SIGNOUT'

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCES'
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL'

export const USER_DETAILS_REQUEST = 'USER_DETAILS_REQUEST'
export const USER_DETAILS_SUCCESS = 'USER_DETAILS_SUCCESS'
export const USER_DETAILS_FAIL = 'USER_DETAILS_FAIL'

export const USER_UPDATE_PROFIL_REQUEST = 'USER_UPDATE_PROFIL_REQUEST' 
export const USER_UPDATE_PROFIL_SUCCESS = 'USER_UPDATE_PROFIL_SUCCESS' 
export const USER_UPDATE_PROFIL_FAIL = 'USER_UPDATE_PROFIL_REQUEST'
export const USER_UPDATE_PROFIL_RESET = 'USER_UPDATE_PROFIL_RESET'