export const USER_SIGNIN_REQUEST = 'USER_SIGNIN_REQUEST'
export const USER_SIGNIN_SUCCES = 'USER_SIGNIN_SUCCES'
export const USER_SIGNIN_FAIL = 'USER_SIGNIN_FAIL'
export const USER_SIGNIN_SIGNOUT = 'USER_SIGNIN_SIGNOUT'